export const USER_INPUT_REG_NAME_CHANGED = 'USER_INPUT_REG_NAME_CHANGED';
export const USER_INPUT_REG_SURNAME_CHANGED = 'USER_INPUT_REG_SURNAME_CHANGED';
export const USER_INPUT_REG_BIRTHDATE_CHANGED = 'USER_INPUT_REG_BIRTHDATE_CHANGED';
export const USER_INPUT_REG_LOGIN_CHANGED = 'USER_INPUT_LOGIN_CHANGED';
export const USER_INPUT_REG_PASSWORD_CHANGED = 'USER_INPUT_REG_PASSWORD_CHANGED';
export const USER_INPUT_REG_PASSWORD2_CHANGED = 'USER_INPUT_REG_PASSWORD2_CHANGED';

export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAILED = 'USER_REGISTRATION_FAILED';
export const USER_RETURN_REGISTER = 'USER_RETURN_REGISTER';

export const USER_INPUT_AUTH_LOGIN_CHANGED = 'USER_INPUT_AUTH_LOGIN_CHANGED';
export const USER_INPUT_AUTH_PASSWORD_CHANGED = 'USER_INPUT_AUTH_PASSWORD_CHANGED';
export const USER_SAVE_AUTH = 'USER_SAVE_AUTH';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILED = 'USER_AUTH_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_INPUT_VALIDATE = 'USER_INPUT_VALIDATE';

export const USER_AUTH_TOKEN_SUCCESS = 'USER_AUTH_TOKEN_SUCCESS';
export const USER_AUTH_TOKEN_FAILED = 'USER_AUTH_TOKEN_FAILED';

export const USER_INFO_NAME_CHANGED = 'USER_INFO_NAME_CHANGED';
export const USER_INFO_SURNAME_CHANGED = 'USER_INFO_SURNAME_CHANGED';
export const USER_INFO_BIRTDATE_CHANGED = 'USER_INFO_BIRTDATE_CHANGED';
export const USER_INFO_PASSWORD_OLD_CHANGED = 'USER_INFO_PASSWORD_OLD_CHANGED';
export const USER_INFO_PASSWORD_CHANGED = 'USER_INFO_PASSWORD_CHANGED';
export const USER_INFO_PASSWORD2_CHANGED = 'USER_INFO_PASSWORD2_CHANGED';
export const USER_INFO_CHANGED_SUCCESS = 'USER_INFO_CHANGED_SUCCESS';
export const USER_INFO_CHANGED_FAILED = 'USER_INFO_CHANGED_FAILED';
export const USER_PASSWORD_CHANGED_SUCCESS = 'USER_PASSWORD_CHANGED_SUCCESS';
export const USER_PASSWORD_CHANGED_FAILED = 'USER_PASSWORD_CHANGED_FAILED';
export const USER_MODAL_EXIT_OPEN = 'USER_MODAL_EXIT_OPEN';
export const USER_MODAL_EXIT_CLOSE = 'USER_MODAL_EXIT_CLOSE';

export const USER_LIKE_SUCCESS = 'USER_LIKE_SUCCESS';
export const USER_LIKE_FAILED = 'USER_LIKE_FAILED';

export const HEADER_MENU_OPEN = 'HEADER_MENU_OPEN';
export const HEADER_MENU_CLOSE = 'HEADER_MENU_CLOSE';

export const STORY_INPUT_TITLE_CHANGED = 'STORY_INPUT_TITLE_CHANGED';
export const STORY_GET_CATEGORIES_SUCCESSFULL = 'STORY_GET_CATEGORIES_SUCCESSFULL';
export const STORY_GET_CATEGORIES_FAILED = 'STORY_GET_CATEGORIES_FAILED';
export const STORY_SELECT_CATEGORY_CHANGED = 'STORY_SELECT_CATEGORY_CHANGED';
export const STORY_INPUT_CONTENT_CHANGED = 'STORY_INPUT_CONTENT_CHANGED';
export const STORY_CHECKBOX_PUBLIC_CHANGED = 'STORY_CHECKBOX_PUBLIC_CHANGED';
export const STORY_CREATE_SUCCESSFULL = 'STORY_CREATE_SUCCESSFULL';
export const STORY_CREATE_FAILED = 'STORY_CREATE_FAILED';
export const STORY_UPDATE_SUCCESSFULL = 'STORY_UPDATE_SUCCESSFULL';
export const STORY_UPDATE_FAILED = 'STORY_UPDATE_FAILED';
export const STORY_DELETE_SUCCESSFUL = 'STORY_DELETE_SUCCESSFUL';
export const STORY_DELETE_FAILED = 'STORY_DELETE_FAILED';
export const STORY_GET_BY_AUTHOR_SUCCESSFULL = 'STORY_GET_BY_AUTHOR_SUCCESSFULL';
export const STORY_GET_BY_AUTHOR_FAILED = 'STORY_GET_BY_AUTHOR_FAILED';
export const STORY_CHANGE_PUBLIC_STATUS = 'STORY_CHANGE_PUBLIC_STATUS';
export const STORY_CHANGE_PUBLIC_STATUS_FAILED = 'STORY_CHANGE_PUBLIC_STATUS_FAILED';
export const STORY_PREPARE_TO_CHANGING = 'STORY_PREPARE_TO_CHANGING';
export const STORY_CHANGE_TITLE = 'STORY_CHANGE_TITLE';
export const STORY_CHANGE_CATEGORY = 'STORY_CHANGE_CATEGORY';
export const STORY_CHANGE_CONTENT = 'STORY_CHANGE_CONTENT';
export const STORY_CHANGE_STATUS = 'STORY_CHANGE_STATUS';
export const STORY_GET_ALL_SUCCESS = 'STORY_GET_ALL_SUCCESS';
export const STORY_GET_ALL_FAILED = 'STORY_GET_ALL_FAILED';
export const STORY_GET_BY_CATEGORY_SUCCESS = 'STORY_GET_BY_CATEGORY_SUCCESS';
export const STORY_GET_BY_CATEGORY_FAILED = 'STORY_GET_BY_CATEGORY_FAILED';
export const STORY_MODAL_DELETE_OPEN = 'STORY_MODAL_DELETE_OPEN';
export const STORY_MODAL_DELETE_CLOSE = 'STORY_MODAL_DELETE_CLOSE';
export const STORY_INPUT_VALIDATE = 'STORY_INPUT_VALIDATE';

export const GENERAL_GET_COMMENTS_FAILED = 'GENERAL_GET_COMMENTS_FAILED';
export const GENERAL_GET_COMMENTS_SUCCESS = 'GENERAL_GET_COMMENTS_SUCCESS';
export const GENERAL_GET_LIKES_FAILED = 'GENERAL_GET_LIKES_FAILED';
export const GENERAL_GET_LIKES_SUCCESS = 'GENERAL_GET_LIKES_SUCCESS';
export const GENERAL_GET_ALL_LIKES_FAILED = 'GENERAL_GET_ALL_LIKES_FAILED';
export const GENERAL_GET_ALL_LIKES_SUCCESS = 'GENERAL_GET_ALL_LIKES_SUCCESS';
export const GENERAL_CHANGE_CATEGORY = 'GENERAL_CHANGE_CATEGORY';
export const GENERAL_CLOSE_SNACK = 'GENERAL_CLOSE_SNACK';